version: "4.0"

services:
  frontend:
    container_name: my-next-app
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - .:/app

    command: npm run dev
