import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { useRef } from "react";
import { Provider } from "react-redux";
import { makeStore } from "./store/store";
import StoreProvider from "./StoreProvider";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <StoreProvider>
          <div>{children}</div>
        </StoreProvider>
      </body>
    </html>
  );
}
